export const environment = {
  production: true,

  // Money URLs
  moneyTransactionListPage: "money/transaction/list/page",
  moneyTransactionUrlFormat: "money/transaction?sortAscending=false&type=##type##[from][to][account][category]",
  moneyCategoryUrl: "money/categories",
  moneyAccountUrl: "money/accounts",
  moneyAddUrl: "money/transaction",
  moneyTypeUrl: "api/money/types.json",
  moneyStatementUrl: "money/statement",
  moneyUpdateTransactionUrl: "money/transaction",
  moneyDeleteTransactionUrl: "money/transaction",
  moneyLockStatementUrl: "money/statement/lock",
  moneyReconcileTransactionUrl: "money/reconcile",
  moneyMatchUrl: "money/match",
  moneyClearDataUrl: "money/reconciliation/clear",
  moneyAutoAcceptUrl: "money/reconciliation/auto",
  moneySetCategoryUrl: "money/reconciliation/update",
  moneyGetRegularUrl: "money/transaction/regulars",
  moneyGetFilesUrl: "money/reconciliation/files",
  moneyLoadFileUrl: "money/reconciliation/load",
  moneyAccountImage: "money/account/logo?disabled=false&id=##id##",
  moneyAccountDisabledImage: "money/account/logo?disabled=true&id=##id##",
  moneyFileUpdates: "money/reconciliation/file-updates",
  moneyVersion: 'money/version',

  // Backup URLs
  backupGetPreImportFiles: "backup/import/files",
  backupFileUpdates: "backup/import/events/files",
  backupFileSummaryUpdates: "backup/import/events/summary",
  backupRemoveIgnored: "backup/import/ignored",
  backupRemoveActive: "backup/import/active-photos",
  backupImportPhotos: "backup/import/photos",
  backupDeleteConfirmedImports: "backup/import/confirmed",
  backupIgnoreFile: "backup/import/file/ignore",
  backupUnignoreFile: "backup/import/file/un-ignore",
  backupDeleteImportFile: "backup/import/file",
  backupUpdateDestination: "backup/import/file/destination",
  backupRecipeFile: "backup/import/file/recipe",
  basicBackupFile: "backup/import/file/backup",
  backupSummary: "backup/summary",
  backupActions: "backup/actions",
  backupHierarchy: "backup/hierarchy",
  backupPrintSize: "backup/prints/sizes",
  backupPrint: "backup/prints",
  backupPrints: "backup/prints",
  backupRefreshFile: "backup/files/refresh?id=##id##",
  backupLabels: "backup/labels",
  backupLabel: "backup/labels",
  backupExpire: "backup/files/expire",
  backupUnprint: "backup/prints/unselect",
  backupLog: "backup/logs"
};
