export const environment = {
  production: true,

  // Money URLs
  moneyTransactionList: "money/transaction/list",
  moneyTransactionUrlFormat: "money/transaction?sortAscending=false&type=##type##[from][to][account][category]",
  moneyCategoryUrl: "money/categories",
  moneyAccountUrl: "money/accounts",
  moneyAddUrl: "money/transaction",
  moneyTypeUrl: "api/money/types.json",
  moneyStatementUrl: "money/statement",
  moneyUpdateTransactionUrl: "money/transaction",
  moneyDeleteTransactionUrl: "money/transaction",
  moneyLockStatementUrl: "money/statement/lock",
  moneyReconcileTransactionUrl: "money/reconcile",
  moneyMatchUrl: "money/match",
  moneyClearDataUrl: "money/reconciliation/clear",
  moneyAutoAcceptUrl: "money/reconciliation/auto",
  moneySetCategoryUrl: "money/reconciliation/update",
  moneyGetRegularUrl: "money/transaction/regulars",
  moneyGetFilesUrl: "money/reconciliation/files",
  moneyLoadFileUrl: "money/reconciliation/load",
  moneyAccountImage: "money/account/logo?disabled=false&id=##id##",
  moneyAccountDisabledImage: "money/account/logo?disabled=true&id=##id##",
  moneyFileUpdates: "money/reconciliation/file-updates",

  // Backup URLs
  backupGetPreImportFiles: "backup/import-files",
  backupFileUpdates: "backup/file-updates",
  backupFileSummaryUpdates: "backup/summary-updates",
  backupReimportFile: "backup/reimportfile",
  backupRemoveIgnored: "backup/delete-ignored",
  backupRemoveActive: "backup/delete-active-photos",
  backupImportPhotos: "backup/import-photos",
  backupDeleteConfirmedImports: "backup/delete-confirmed-imports",
  backupProcessFiles: "backup/importprocess",
  backupIgnoreFile: "backup/ignore-file",
  backupUnignoreFile: "backup/un-ignore-file",
  backupDeleteImportFile: "backup/delete-import-file",
  backupUpdateDestination: "backup/update-destination",
  backupRecipeFile: "backup/recipe-file",
  backupSummary: "backup/summary",
  backupActions: "backup/actions",
  backupHierarchy: "backup/hierarchy",
  backupPrintSize: "backup/print-size",
  backupPrint: "backup/print",
  backupPrints: "backup/prints",
  backupRefreshFile: "backup/refresh-file-data?id=##id##",
  backupLabels: "backup/labels",
  backupLabel: "backup/label",
  backupExpire: "backup/expire",
  backupUnprint: "backup/unprint",
  backupLog: "backup/log"
};
